### ISSUE TITLE
broken...

### ISSUE THREAD

**Issue by matty234** [andrewnicolalde/i3-config#1]
## Description
Using i3 is alot of irelevant and unecessary work to configure and maintain.

## Expected Behavior
Have a display manager that just kinda opens windows when you open an application and closes them when you click close.

## Actual Behavior
You end up creating a git repo with you configuration options that took real time to write that could be spent on more important things, like removing the crusty bits between your keyboard or thinking of all the rhyming words with cane (Mark Twain, lane, etc...)

## Possible Fix
Buy a Mac

## Steps to Reproduce
1. Talk to @AwenSaunders 
2. Accidentally install Arch
3. Create git repo to store your i3 configuration
4. Everything breaks
5. Buy a Mac

**Comment by awensaunders** [comment]
Can confirm.

Side note: having public repos for this is very annoying... would suggest to look at GNU Stow for management of dotfiles so there is just one for all of your configs

**Comment by andrewnicolalde** [comment]
@awensaunders Thanks for the suggestion. I'll look into that.

**Comment by andrewnicolalde** [comment]
https://github.com/andrewnicolalde/dotfiles
